name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go build cmd/gocertmgr.go
      - run: |
          echo '{"rootdir": "."}' >certmgr.json
          ./gocertmgr createkeyandcert -cn "Test CA" -selfsigned ca testca
          ./gocertmgr createkeyandcsr intermediateca
          ./gocertmgr signcsr -cn "Intermediate CA" -signer testca ca intermediateca
          ./gocertmgr createkeyandcert -cn "Server Cert" -dns testserver.example.com -signer intermediateca server servercert
          ./gocertmgr createkeyandcert -cn "Client Cert" -signer testca client clientcert
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux
          - darwin
          - windows
        arch:
          - amd64
    steps:
      - uses: actions/checkout@v4
      - run: go build -o "gocertmgr-${{ matrix.platform }}-${{ matrix.arch }}" cmd/gocertmgr.go
        env:
          GOOS: "${{ matrix.platform }}"
          GOARCH: "${{ matrix.arch }}"
      - uses: actions/upload-artifact@v4
        with:
          name: "gocertmgr-${{ matrix.platform }}-${{ matrix.arch }}"
          path: "gocertmgr-${{ matrix.platform }}-${{ matrix.arch }}"
