name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go build cmd/gocertmgr.go
      
      - name: Test valid gocertmgr flag, commands and arguments
        run: |
          echo '{"rootdir": "."}' >certmgr.json
          ./gocertmgr createkeyandcert -cn "Test CA" -selfsigned ca testca
          ./gocertmgr createkeyandcsr intermediateca
          ./gocertmgr signcsr -cn "Intermediate CA" -signer testca ca intermediateca
          ./gocertmgr createkeyandcert -cn "Server Cert" -dns testserver.example.com -signer intermediateca server servercert
          ./gocertmgr createkeyandcert -cn "Client Cert" -signer testca client clientcert

      - name: Test gocertmgr flag, commands and arguments
        run: |
          ./gocertmgr invalidcommand || echo "Invalid command handled correctly"
          ./gocertmgr createkeyandcert || echo "Missing args handled correctly"
          ./gocertmgr createkeyandcert -cn "Invalid" -selfsigned invalid testinvalid || echo "Invalid cert type handled correctly"
          ./gocertmgr createkeyandcert -cn "Test" -signer nonexistent server test || echo "Invalid signer handled correctly"
          ./gocertmgr createkeyandcert -cn "Test" -dns "invalid..dns" -signer testca server test || echo "Invalid DNS handled correctly"

  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux
          - darwin
          - windows
        arch:
          - amd64
    steps:
      - uses: actions/checkout@v4
      - run: go build -o "gocertmgr-${{ matrix.platform }}-${{ matrix.arch }}" cmd/gocertmgr.go
        env:
          GOOS: "${{ matrix.platform }}"
          GOARCH: "${{ matrix.arch }}"
      - uses: actions/upload-artifact@v4
        with:
          name: "gocertmgr-${{ matrix.platform }}-${{ matrix.arch }}"
          path: "gocertmgr-${{ matrix.platform }}-${{ matrix.arch }}"
